language: java
jdk:
  - openjdk11

# 어느 브랜치가 푸시될 때 수행할 지 결정
branches:
  only:
    - main

# 빌드 전 gradlew 권한 추가
before_install:
  - cd capstone
  - chmod +x ./gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# deploy 명령어 실행 전
before_deploy:
  - zip -r freelec-alddeulsinbang al_ddeul_sin_bang
  - mkdir -p deploy
  - mv freelec-alddeulsinbang.zip deploy/freelec-alddeulsinbang.zip

# S3로 파일 업로드 및 CodeDeploy로 배포 등 외부 서비스와 연동
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_id: $AWS_SECRET_KEY
    bucket: freelec-alddeulsinbang-build #S3 bucket
    region: ap-northeast-2
    skip_cleanup: true 
    acl: private # zip 파일 접근
    local_dir: deploy # before_deploy에서 생성한 디렉터리
    wait-until-deployed: true
    on:
      all_branches: true

# CI 실행 완료 시 메일로 알람
notification:
  email:
    recipients:
      - gettls@daum.net