language: java
jdk:
  - openjdk11

# 어느 브랜치가 푸시될 때 수행할 지 결정
branches:
  only:
    - main

# 빌드 전 gradlew 권한 추가
before_install:
  - chmod +x capstone/gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notification:
  email:
    recipients:
      - gettls@daum.net